/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequestDto"];
                    "text/json": components["schemas"]["LoginRequestDto"];
                    "application/*+json": components["schemas"]["LoginRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponseDto"];
                        "application/json": components["schemas"]["LoginResponseDto"];
                        "text/json": components["schemas"]["LoginResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/x-www-form-urlencoded": {
                        ContentType?: string;
                        ContentDisposition?: string;
                        Headers?: {
                            [key: string]: string[];
                        };
                        /** Format: int64 */
                        Length?: number | string;
                        Name?: string;
                        FileName?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PartyListDto"][];
                        "application/json": components["schemas"]["PartyListDto"][];
                        "text/json": components["schemas"]["PartyListDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkCreationRequest"];
                    "text/json": components["schemas"]["WorkCreationRequest"];
                    "application/*+json": components["schemas"]["WorkCreationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkCreationResponse"];
                        "application/json": components["schemas"]["WorkCreationResponse"];
                        "text/json": components["schemas"]["WorkCreationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequestDto: {
            username: string;
            password: string;
        };
        LoginResponseDto: {
            token: string;
            user: components["schemas"]["UserDto"];
        };
        MediaItemCreationRequest: {
            fileHash: string;
            description?: string;
            mediaType: components["schemas"]["MediaItemType"];
            textContent?: string;
            mimeType: string;
            /** Format: int64 */
            fileSize: number | string;
            /** Format: int32 */
            order: number | string;
            kind: components["schemas"]["MediaItemKind"];
            /** Format: int32 */
            width?: null | number | string;
            /** Format: int32 */
            height?: null | number | string;
        };
        /** @enum {unknown} */
        MediaItemKind: "MAIN" | "EXTRA";
        /** @enum {unknown} */
        MediaItemType: "IMAGE" | "VIDEO" | "AUDIO" | "TEXT";
        MediaItemUploadInfo: {
            /** Format: uuid */
            mediaItemId: string;
            fileHash: string;
            uploadURL: string;
        };
        PartyAliasDto: {
            aliasName: string;
            aliasNormalizedName: string;
        };
        PartyListDto: {
            /** Format: uuid */
            partyId: string;
            partyName: string;
            partyNormalizedName: string;
            partyAliases: components["schemas"]["PartyAliasDto"][];
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        UserDto: {
            id: string;
            userName: string;
            roles: string[];
        };
        WorkCreationCredit: {
            /** Format: uuid */
            partyId: string;
            role: components["schemas"]["WorkCreditRole"];
        };
        WorkCreationRequest: {
            title: string;
            description?: string;
            credits: components["schemas"]["WorkCreationCredit"][];
            novelContent?: string;
            medium: components["schemas"]["WorkMedium"];
            type: components["schemas"]["WorkType"];
            visibility: components["schemas"]["WorkVisibility"];
            rating: components["schemas"]["WorkRating"];
            isAI: boolean;
            /** Format: date-time */
            releasedAt?: null | string;
            coverHash?: null | string;
            coverMimeType?: null | string;
            /** Format: int32 */
            coverWidth?: null | number | string;
            /** Format: int32 */
            coverHeight?: null | number | string;
            mediaItems: components["schemas"]["MediaItemCreationRequest"][];
        };
        WorkCreationResponse: {
            /** Format: uuid */
            workId: string;
            coverUploadURL?: null | string;
            mediaItems: components["schemas"]["MediaItemUploadInfo"][];
        };
        /** @enum {unknown} */
        WorkCreditRole: "ARTIST" | "STUDIO";
        /** @enum {unknown} */
        WorkMedium: "IMAGE" | "VIDEO" | "AUDIO" | "TEXT";
        /** @enum {unknown} */
        WorkRating: "GENERAL" | "MATURE" | "ADULT";
        /** @enum {unknown} */
        WorkType: "ILLUSTRATION" | "MANGA" | "WEBTOON" | "COMIC" | "PHOTOSET" | "ANIME" | "OVA" | "PMV" | "HMV" | "CONCERT" | "VIDEO" | "MUSIC" | "ASMR" | "NOVEL" | "LIGHT_NOVEL" | "TEXTONLY" | "PORN" | "JAV";
        /** @enum {unknown} */
        WorkVisibility: "PUBLIC" | "HIDDEN";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
