/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequestDto"];
                    "text/json": components["schemas"]["LoginRequestDto"];
                    "application/*+json": components["schemas"]["LoginRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponseDto"];
                        "application/json": components["schemas"]["LoginResponseDto"];
                        "text/json": components["schemas"]["LoginResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CharacterListModel"][];
                        "application/json": components["schemas"]["CharacterListModel"][];
                        "text/json": components["schemas"]["CharacterListModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCharacterRequest"];
                    "text/json": components["schemas"]["CreateCharacterRequest"];
                    "application/*+json": components["schemas"]["CreateCharacterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserDto"];
                        "application/json": components["schemas"]["UserDto"];
                        "text/json": components["schemas"]["UserDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PartyListModel"][];
                        "application/json": components["schemas"]["PartyListModel"][];
                        "text/json": components["schemas"]["PartyListModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePartyRequest"];
                    "text/json": components["schemas"]["CreatePartyRequest"];
                    "application/*+json": components["schemas"]["CreatePartyRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WorkCreationRequest"];
                    "text/json": components["schemas"]["WorkCreationRequest"];
                    "application/*+json": components["schemas"]["WorkCreationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkCreationResponse"];
                        "application/json": components["schemas"]["WorkCreationResponse"];
                        "text/json": components["schemas"]["WorkCreationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CharacterAliasModel: {
            aliasName: string;
            aliasNormalizedName: string;
        };
        CharacterListModel: {
            /** Format: uuid */
            characterId: string;
            characterName: string;
            characterNormalizedName: string;
            /** Format: uuid */
            seriesId: string;
            /** Format: uuid */
            creatorPartyId?: null | string;
            characterAliases: components["schemas"]["CharacterAliasModel"][];
        };
        CreateCharacterRequest: {
            name: string;
            /** Format: uuid */
            seriesId: string;
            /** Format: uuid */
            creatorPartyId?: null | string;
        };
        CreatePartyRequest: {
            name: string;
            partyType: components["schemas"]["PartyType"];
        };
        LoginRequestDto: {
            username: string;
            password: string;
        };
        LoginResponseDto: {
            token: string;
            user: components["schemas"]["UserDto"];
        };
        MediaItemCreationRequest: {
            simpleBlake3?: null | string;
            description?: string;
            mediaType: components["schemas"]["MediaItemType"];
            textContent?: string;
            /** Format: int32 */
            order: number | string;
            mimeType?: null | string;
            /** Format: int64 */
            fileSize?: null | number | string;
            originalFileName?: null | string;
            kind: components["schemas"]["MediaItemKind"];
        };
        /** @enum {unknown} */
        MediaItemKind: "Main" | "Extra";
        /** @enum {unknown} */
        MediaItemType: "Image" | "Video" | "Audio" | "Text";
        MediaItemUploadInfo: {
            simpleBlake3Id: string;
            fileName: string;
            multipartUploadInfo: components["schemas"]["MultipartUploadInfo"];
        };
        MultipartUploadInfo: {
            uploadId: string;
            fileID: string;
            /** Format: int64 */
            partSizeInBytes: number | string;
            parts: components["schemas"]["MultipartUploadPartInfo"][];
        };
        MultipartUploadPartInfo: {
            /** Format: int32 */
            partNumber: number | string;
            url: string;
        };
        PartyAliasModel: {
            aliasName: string;
            aliasNormalizedName: string;
        };
        PartyListModel: {
            /** Format: uuid */
            partyId: string;
            partyName: string;
            partyNormalizedName: string;
            partyAliases: components["schemas"]["PartyAliasModel"][];
        };
        /** @enum {unknown} */
        PartyType: "Individual" | "Group" | "Organization" | "Studio";
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        UserDto: {
            id: string;
            userName: string;
            roles: string[];
        };
        WorkCreationCredit: {
            /** Format: uuid */
            partyId: string;
            role: components["schemas"]["WorkCreditRole"];
        };
        WorkCreationRequest: {
            title: string;
            description?: string;
            credits: components["schemas"]["WorkCreationCredit"][];
            characterIds: string[];
            novelContent?: string;
            medium: components["schemas"]["WorkMedium"];
            type: components["schemas"]["WorkType"];
            visibility: components["schemas"]["WorkVisibility"];
            rating: components["schemas"]["WorkRating"];
            isAI: boolean;
            /** Format: date-time */
            releasedAt?: null | string;
            mediaItems: components["schemas"]["MediaItemCreationRequest"][];
        };
        WorkCreationResponse: {
            /** Format: uuid */
            workId: string;
            title: string;
            mediaItems: components["schemas"]["MediaItemUploadInfo"][];
        };
        /** @enum {unknown} */
        WorkCreditRole: "Artist";
        /** @enum {unknown} */
        WorkMedium: "Image" | "Video" | "Audio" | "Text";
        /** @enum {unknown} */
        WorkRating: "General" | "Mature" | "Adult";
        /** @enum {unknown} */
        WorkType: "ILLUSTRATION" | "MANGA" | "WEBTOON" | "COMIC" | "PHOTOSET" | "ANIME" | "OVA" | "PMV" | "HMV" | "CONCERT" | "VIDEO" | "MUSIC" | "ASMR" | "NOVEL" | "LIGHT_NOVEL" | "TEXTONLY" | "PORN" | "JAV";
        /** @enum {unknown} */
        WorkVisibility: "Public" | "Hidden";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
